# Generated by Django 5.0 on 2024-05-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_booking_assign_work_alter_booking_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
