# Generated by Django 5.0 on 2024-05-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_booking_is_otp_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_token',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
