# Generated by Django 5.0.6 on 2024-05-29 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-uid']},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='expo_token',
            field=models.TextField(default=datetime.datetime(2024, 5, 29, 20, 26, 17, 427407, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
