# Generated by Django 5.0.6 on 2024-06-17 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_bookingproduct_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingproduct',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_prod_det', to='account.booking'),
        ),
    ]
