# Generated by Django 5.0.6 on 2024-06-24 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_bookingproduct_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproduct',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_subadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Hold', 'Hold'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_history', to='account.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
