# Generated by Django 5.0.6 on 2024-06-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_bookinghistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinghistory',
            name='staff_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Hold', 'Hold'), ('Changed', 'Changed'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=50),
        ),
    ]
