# Generated by Django 5.0.6 on 2024-06-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_bookinghistory_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingproduct',
            name='staff_work_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
