# Generated by Django 5.0.6 on 2024-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_bookingproduct_staff_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadminservicearea',
            name='city_name',
            field=models.CharField(max_length=180),
        ),
    ]
