# Generated by Django 5.0 on 2024-05-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityservice',
            name='city_name',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
