# Generated by Django 5.0.6 on 2024-06-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_cityservice_city_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time']},
        ),
    ]
