# Generated by Django 5.0 on 2024-04-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.CharField(max_length=220)),
                ('phone', models.CharField(max_length=220)),
                ('subject', models.CharField(max_length=220)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.CharField(max_length=220)),
                ('city_name', models.CharField(max_length=110)),
                ('service', models.CharField(max_length=220)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=220)),
            ],
        ),
    ]
